### PR TITLE
Many updates to prepare for 2018

### PR DESCRIPTION
**Pull request by jaspervdj**

### CODE REVIEW

**Comment by gleber** [comment]
I think it would be beneficial to keep the old version of the page available somewhere. Can you move old files into e.g. http://zurihac.info/2017/ ?

**Comment by jaspervdj** [comment]
Agreed, I don't really know how to do that using this framework though.  I can rebuild the old site from an old commit and just dump the generated HTML in `/2017` but @wereHamster might know a better way to do that (and also we don't need to do it in this PR).

**Comment by wereHamster** [comment]
The old website is available @ https://zurihac.info/2017, the corresponding version of the website is in the 2017 branch. I've also renamed the repository and taken the year out of the name.

**Comment by jaspervdj** [comment]
Thanks!

**Pull request merged**
